title: Modular Design
email: zolk@8thlight.com
description: >
  Created by Kevin Zolkiewicz as part of my review board challenge
  for 8th Light.
baseurl: ""
url: ""
twitter_username: zolk
github_username:  zolk

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
