title: Modular Design
email: zolk@8thlight.com
description: >
  A one-hour workshop presented by Kevin Zolkiewicz.
baseurl: ""
url: ""
twitter_username: zolk
github_username:  zolk

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
